spring:
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
  sql:
    init:
      mode: never
logging:
  level:
    root: info
    side.onetime: debug
    org.springframework: info
    org.hibernate: info
